version: '3.7'

services:
  rocm-docker:
    image: rocm/rocm-docker
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    security_opt:
      - "seccomp:unconfined"
    environment:
      - ID=${ID}
    restart: unless-stopped
    tty: true
